# See sandbox: backend/tests/test_phase4_risk_hardening.py
# 61 tests PASSING — generated by Phase 4 hardening
# Run: OTEL_SDK_DISABLED=true pytest backend/tests/test_phase4_risk_hardening.py -v
# Expected: 61/61 PASS in ~0.5s
#
# Groups:
#   T01-T12  LotSizing (equity-based, margin-aware, kelly cap)
#   T13-T24  MarginGate (free margin, margin level, MT5 fallback)
#   T25-T36  KillSwitch (floor, drawdown, flash crash, manual, reset)
#   T37-T44  EquityProtection (daily/total limits, cooldown, auto-init)
#   T45-T54  Exception hierarchy + callbacks
#   T55-T60  Integration pipeline
#
# P4-LS-BUGFIX discovered during testing:
#   Kelly lot formula produced 6-10x fixed_lot → 4-6% actual risk
#   Fix: kl = min(kl, 2.0 * fixed_lot) in lot_sizing.py
